### PR TITLE
Shell deployment to heroku

### PR DESCRIPTION
**Pull request by zenfinity**
Changes made to get shell deployment made.

### CODE REVIEW

**Comment by zenfinity** [comment]
Overwrote index.html and added other pages from Kaylene.

**Review by hchuhtala — APPROVED** [review]
Let's merge!

**Comment by zenfinity** [comment]
I don't think anything in the repo root directory matters. Only what's in the recrec_app dir will affect things. And that's only if you want to deploy on your own anyway. :)

**Comment by hchuhtala** [comment]
resolved locally and pushed

**Pull request closed without merging**
